export const matches = [
  {"id":"1","date":"11 iunie, ora 22:00","teams":"Mexic - Africa de Sud"},
  {"id":"2","date":"12 iunie, ora 5:00","teams":"Coreea de Sud - Cehia"},
  {"id":"3","date":"12 iunie, ora 22:00","teams":"Canada - Bosnia"},
  {"id":"4","date":"13 iunie, ora 4:00","teams":"SUA - Paraguay"},
  {"id":"5","date":"13 iunie, ora 22:00","teams":"Qatar - Elveția"},
  {"id":"6","date":"14 iunie, ora 1:00","teams":"Brazilia - Maroc"},
  {"id":"7","date":"14 iunie, ora 4:00","teams":"Haiti - Scoția"},
  {"id":"8","date":"14 iunie, ora 7:00","teams":"Australia - Turcia"},
  {"id":"9","date":"14 iunie, ora 20:00","teams":"Germania - Curacao"},
  {"id":"10","date":"14 iunie, ora 23:00","teams":"Olanda - Japonia"},
  {"id":"11","date":"15 iunie, ora 2:00","teams":"Coasta de Fildeș - Ecuador"},
  {"id":"12","date":"15 iunie, ora 5:00","teams":"Suedia - Tunisia"},
  {"id":"13","date":"15 iunie, ora 19:00","teams":"Spania - Insulele Capului Verde"},
  {"id":"14","date":"15 iunie, ora 22:00","teams":"Belgia - Egipt"},
  {"id":"15","date":"16 iunie, ora 1:00","teams":"Arabia Saudită - Uruguay"},
  {"id":"16","date":"16 iunie, ora 4:00","teams":"Iran - Noua Zeelandă"},
  {"id":"17","date":"16 iunie, ora 22:00","teams":"Franța - Senegal"},
  {"id":"18","date":"17 iunie, ora 1:00","teams":"Irak - Norvegia"},
  {"id":"19","date":"17 iunie, ora 4:00","teams":"Argentina - Algeria"},
  {"id":"20","date":"17 iunie, ora 7:00","teams":"Austria - Iordania"},
  {"id":"21","date":"17 iunie, ora 20:00","teams":"Portugalia - RD Congo"},
  {"id":"22","date":"17 iunie, ora 23:00","teams":"Anglia - Croația"},
  {"id":"23","date":"18 iunie, ora 2:00","teams":"Ghana - Panama"},
  {"id":"24","date":"18 iunie, ora 5:00","teams":"Uzbekistan - Columbia"},
  {"id":"25","date":"18 iunie, ora 19:00","teams":"Cehia - Africa de Sud"},
  {"id":"26","date":"18 iunie, ora 22:00","teams":"Elveția - Bosnia"},
  {"id":"27","date":"19 iunie, ora 1:00","teams":"Canada - Qatar"},
  {"id":"28","date":"19 iunie, ora 4:00","teams":"Mexic - Coreea de Sud"},
  {"id":"29","date":"19 iunie, ora 22:00","teams":"SUA - Australia"},
  {"id":"30","date":"20 iunie, ora 1:00","teams":"Scoția - Maroc"},
  {"id":"31","date":"20 iunie, ora 3:30","teams":"Brazilia - Haiti"},
  {"id":"32","date":"20 iunie, ora 6:00","teams":"Turcia - Paraguay"},
  {"id":"33","date":"20 iunie, ora 20:00","teams":"Olanda - Suedia"},
  {"id":"34","date":"20 iunie, ora 23:00","teams":"Germania - Coasta de Fildeș"},
  {"id":"35","date":"21 iunie, ora 3:00","teams":"Ecuador - Curacao"},
  {"id":"36","date":"21 iunie, ora 7:00","teams":"Tunisia - Japonia"},
  {"id":"37","date":"21 iunie, ora 19:00","teams":"Spania - Arabia Saudită"},
  {"id":"38","date":"21 iunie, ora 22:00","teams":"Belgia - Iran"},
  {"id":"39","date":"22 iunie, ora 1:00","teams":"Uruguay - Insulele Capului Verde"},
  {"id":"40","date":"22 iunie, ora 4:00","teams":"Noua Zeelandă - Egipt"},
  {"id":"41","date":"22 iunie, ora 20:00","teams":"Argentina - Austria"},
  {"id":"42","date":"23 iunie, ora 0:00","teams":"Franța - Irak"},
  {"id":"43","date":"23 iunie, ora 3:00","teams":"Norvegia - Senegal"},
  {"id":"44","date":"23 iunie, ora 6:00","teams":"Iordania - Algeria"},
  {"id":"45","date":"23 iunie, ora 20:00","teams":"Portugalia - Uzbekistan"},
  {"id":"46","date":"23 iunie, ora 23:00","teams":"Anglia - Ghana"},
  {"id":"47","date":"24 iunie, ora 2:00","teams":"Panama - Croația"},
  {"id":"48","date":"24 iunie, ora 5:00","teams":"Columbia - RD Congo"},
  {"id":"49","date":"24 iunie, ora 22:00","teams":"Elveția - Canada"},
  {"id":"50","date":"24 iunie, ora 22:00","teams":"Bosnia - Qatar"},
  {"id":"51","date":"25 iunie, ora 1:00","teams":"Scoția - Brazilia"},
  {"id":"52","date":"25 iunie, ora 1:00","teams":"Maroc - Haiti"},
  {"id":"53","date":"25 iunie, ora 4:00","teams":"Africa de Sud - Coreea de Sud"},
  {"id":"54","date":"25 iunie, ora 4:00","teams":"Cehia - Mexic"},
  {"id":"55","date":"25 iunie, ora 23:00","teams":"Ecuador - Germania"},
  {"id":"56","date":"25 iunie, ora 23:00","teams":"Curacao - Coasta de Fildeș"},
  {"id":"57","date":"26 iunie, ora 2:00","teams":"Tunisia - Olanda"},
  {"id":"58","date":"26 iunie, ora 2:00","teams":"Japonia - Suedia"},
  {"id":"59","date":"26 iunie, ora 5:00","teams":"Paraguay - Australia"},
  {"id":"60","date":"26 iunie, ora 5:00","teams":"Turcia - SUA"},
  {"id":"61","date":"26 iunie, ora 22:00","teams":"Norvegia - Franța"},
  {"id":"62","date":"26 iunie, ora 22:00","teams":"Senegal - Irak"},
  {"id":"63","date":"27 iunie, ora 3:00","teams":"Uruguay - Spania"},
  {"id":"64","date":"27 iunie, ora 3:00","teams":"Insulele Capului Verde - Arabia Saudită"},
  {"id":"65","date":"27 iunie, ora 6:00","teams":"Noua Zeelandă - Belgia"},
  {"id":"66","date":"27 iunie, ora 6:00","teams":"Egipt - Iran"},
  {"id":"67","date":"28 iunie, ora 0:00","teams":"Panama - Anglia"},
  {"id":"68","date":"28 iunie, ora 0:00","teams":"Croația - Ghana"},
  {"id":"69","date":"28 iunie, ora 2:30","teams":"Columbia - Portugalia"},
  {"date":"28 iunie, ora 2:30","teams":"RD Congo - Uzbekistan"},
  {"date":"28 iunie, ora 5:00","teams":"Iordania - Argentina"},
  {"date":"28 iunie, ora 5:00","teams":"Algeria - Austria"}
].map((m, index) => ({ ...m, id: (index + 1).toString(), team_home: m.teams.split(' - ')[0], team_away: m.teams.split(' - ')[1] }));
